# The `meta`, `result` and `feedback` fields are reserved for the standard
# and must always be present.

std_skills/Meta meta
string scan_id
---
std_skills/Result result
int64 result_s
---
std_skills/Feedback feedback
