# The `meta`, `result` and `feedback` fields are reserved for the standard
# and must always be present.

std_skills/Meta meta
string skill_data
---
std_skills/Result result
string value
---
std_skills/Feedback feedback
