import time

from rclpy.lifecycle import Node
from rclpy.lifecycle import State
from rclpy.lifecycle import TransitionCallbackReturn
from rcl_interfaces.msg import ParameterDescriptor

from rclpy.action import ActionServer, GoalResponse

# this is an example of a custom skill action message generated by
# rpk. We use it to create our API to start/stop the skill
from mesh_skill_msgs.action import Mesh

from diagnostic_msgs.msg import DiagnosticArray, DiagnosticStatus, KeyValue


class MeshSkillImpl(Node):

    def __init__(self) -> None:

        super().__init__('skill_mesh')

        self.declare_parameter(
            'parameter_name', 'parameter_value',
            ParameterDescriptor(description='A parameter for the skill')
        )

        self.get_logger().info("Initialising...")
        self._timer = None
        self._diag_pub = None
        self._diag_timer = None

        self._nb_requests = 0

        self.get_logger().info('Skill mesh started, but not yet configured.')

    def run_skill(self):

        self.get_logger().info("...running the skill")

        time.sleep(1)

        result = "this is an important result"

        return result

    def on_request_goal(self, goal_handle):

        if self._state_machine.current_state[1] != "active":
            self.get_logger().error("Skill is not active yet, rejecting goal")
            return GoalResponse.REJECT

        self.get_logger().info("Accepted a new goal")
        return GoalResponse.ACCEPT

    def on_request_exec(self, goal_handle):

        self.get_logger().info(f"Executing the skill with data: {goal_handle.request.skill_data}")


        res = self.run_skill()

        self.get_logger().info("Goal executed successfully")
        goal_handle.succeed()

        return Mesh.Result(value=f"{res}")

    def on_configure(self, state: State) -> TransitionCallbackReturn:

        self._nb_requests = 0

        self.skill_server = ActionServer(self,
                                         Mesh,
                                         "/skill/mesh",
                                         goal_callback=self.on_request_goal,
                                         execute_callback=self.on_request_exec)

        self._diag_pub = self.create_publisher(DiagnosticArray, '/diagnostics', 1)
        self._diag_timer = self.create_timer(1., self.publish_diagnostics)

        self.get_logger().info("Skill mesh is configured, but not yet active")
        return TransitionCallbackReturn.SUCCESS

    def on_activate(self, state: State) -> TransitionCallbackReturn:

        timer_period = 1  # in sec
        self._timer = self.create_timer(timer_period, self.run)

        self.get_logger().info("Skill mesh is active and running")
        return super().on_activate(state)

    def on_deactivate(self, state: State) -> TransitionCallbackReturn:
        self.get_logger().info("Stopping skill...")
        self.destroy_timer(self._timer)

        self.get_logger().info("Skill mesh is stopped (inactive)")
        return super().on_deactivate(state)

    def on_shutdown(self, state: State) -> TransitionCallbackReturn:

        self.get_logger().info('Shutting down mesh skill.')

        self.skill_server.destroy()

        self.destroy_timer(self._diag_timer)
        self.destroy_publisher(self._diag_pub)

        self.get_logger().info("Skill mesh finalized.")
        return TransitionCallbackReturn.SUCCESS

    #################################

    def publish_diagnostics(self):

        arr = DiagnosticArray()
        msg = DiagnosticStatus(
            level=DiagnosticStatus.OK,
            name="/skill/mesh",
            message="skill mesh is running",
            values=[
                KeyValue(key="Module name", value="mesh"),
                KeyValue(key="Current lifecycle state",
                         value=self._state_machine.current_state[1]),
                KeyValue(key="# invokations", value=str(self._nb_requests)),
            ],
        )

        arr.header.stamp = self.get_clock().now().to_msg()
        arr.status = [msg]
        self._diag_pub.publish(arr)

    def run(self) -> None:
          self.get_logger().info("skill mesh: performing background task...")
